library(quantmod)
library(Quandl)
library(plotly)
library(xlsx)
sp500 <- new.env()
getSymbols("^GSPC",env=sp500,src="yahoo",from = as.Date("2000-01-01"),to=as.Date("2018-01-01"))
nasdaq100 <- read.csv("nasdaq100list.csv", stringsAsFactors = FALSE, strip.white = TRUE)
dim(nasdaq100)
names(nasdaq100)
nasdaq100$Name[duplicated(nasdaq100$Name)]
View(nasdaq100)
nasdaq <- new.env()
nasdaq <- new.env()
for(i in nasdaq100$Symbol[startsWith(nasdaq100$Symbol, "A")]) { cat("Downloading time series for symbol '", i, "' ...\n", \n", sep="")status <- tryCatch <- tryCatch(getSymbols(i, env = nasdaq, src = "yahoo", from = as.Date("2000-01-01")),error = identity) if(inherits(status, "error"))cat("Symbol '", i, "' not downloadable!\n", sep = "")}
with(nasdaq, head(AAPL))
chartSeries(nasdaq$AAPL)
library(xts)
View(nasdaq100)
require("quantmod")
sp500 <- new.env()
View(nasdaq)
View(sp500)
View(nasdaq100)
getSymbols("AAPL",env=sp500,src="yahoo",from = as.Date("2000-01-01"),to=as.Date("2018-01-01"))
View(sp500)
View(nasdaq)
View(nasdaq100)
getSymbols(src="yahoo")
getSymbols("AAPL", from="2000-01-01")
View(AAPL)
plot(AAPL[,4])
chartSeries(AAPL, subset='last 6 months',
theme = chartTheme("white"))
getSymbols(src='yahoo')
getSymbols("GOOG",from="2000-01-01")
plot(GOOG)
View(GOOG)
plot(GOOG[,4])
chartSeries(GOOG, subset='last 6 months',
theme = chartTheme("white"))
library(xlsx)
write.xlsx(AAPL, file="AAPL.xlsx", sheetName="AAPL",
col.names=TRUE, row.names=TRUE, append=FALSE, showNA=TRUE, password=NULL)
write.xlsx(GOOG, file="GOOG.xlsx", sheetName="GOOG",
col.names=TRUE, row.names=TRUE, append=FALSE, showNA=TRUE, password=NULL)
savehistory("C:/Users/ricar/Downloads/R/APPLE/r_code.Rhistory")
savehistory("C:/Users/ricar/Downloads/R/APPLE/aapl_goog.r")
library(quantmod)
library(Quandl)
library(plotly)
library(xlsx)
getSymbols(src="yahoo")
getSymbols("AMZN", from="2000-01-01")
plot(AMZN[,4])
chartSeries(AMZN, subset='last 6 months',
theme = chartTheme("white"))
write.xlsx(AMZN, file="AMZN.xlsx", sheetName="AMZN",
col.names=TRUE, row.names=TRUE, append=FALSE, showNA=TRUE, password=NULL)
View(AMZN)
View(AMZN)
View(AMZN)
savehistory("C:/Users/ricar/Downloads/R/APPLE/amazon_code.r")
